# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(181719)
$foreground = rgb(EDECF2)
$color0 = rgb(3F3E40)
$color1 = rgb(131017)
$color2 = rgb(14131B)
$color3 = rgb(2F3350)
$color4 = rgb(7F3B2E)
$color5 = rgb(997A6E)
$color6 = rgb(9896A4)
$color7 = rgb(DDDBE5)
$color8 = rgb(9A99A0)
$color9 = rgb(19161F)
$color10 = rgb(1B1924)
$color11 = rgb(3E446A)
$color12 = rgb(AA4E3D)
$color13 = rgb(CCA293)
$color14 = rgb(CBC8DB)
$color15 = rgb(DDDBE5)
