# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(231C2E)
$foreground = rgb(EAEAEA)
$color0 = rgb(4B4256)
$color1 = rgb(2B2C2C)
$color2 = rgb(4C416E)
$color3 = rgb(5C5C5D)
$color4 = rgb(6B657E)
$color5 = rgb(929292)
$color6 = rgb(929292)
$color7 = rgb(D9D8D9)
$color8 = rgb(989798)
$color9 = rgb(393A3A)
$color10 = rgb(655792)
$color11 = rgb(7B7B7C)
$color12 = rgb(8F86A8)
$color13 = rgb(C3C2C3)
$color14 = rgb(C3C2C3)
$color15 = rgb(D9D8D9)
