# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/99-Readable.conf

font_family JetBrainsMono Nerd Font Mono
font_size 13.0
bold_font JetBrainsMono Nerd Font Mono Bold
italic_font auto
bold_italic_font auto

background_opacity 1.0
dynamic_background_opacity 0
confirm_os_window_close 0

# Animated cursor
cursor_trail 3

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4
