# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EDECF2
background         #181719
cursor             #84828B

active_tab_foreground     #181719
active_tab_background     #EDECF2
inactive_tab_foreground   #EDECF2
inactive_tab_background   #181719

active_border_color   #EDECF2
inactive_border_color #181719
bell_border_color     #131017

color0      #3F3E40
color1		#131017
color2		#14131B
color3		#2F3350
color4		#7F3B2E
color5		#997A6E
color6		#9896A4
color7		#DDDBE5
color8		#9A99A0
color9		#19161F
color10		#1B1924
color11		#3E446A
color12		#AA4E3D
color13		#CCA293
color14		#CBC8DB
color15		#DDDBE5
